####################################################################################################
# Duplicate inspection - Function and inspection                                                   #
# Input: Any and all df's with ID's mentioned in the pairs section                                 #
# Output (function): Print-out of rows of potential duplicate data                                 #
# Output (variables; see section 5): ID's matched, for inclusion, and for exclusion, task-wise     #
# Meta-output: Flagging of all kept data from this, to be presented without this in supplimentary  #
# Note: Pairs are made from meta-data in source-data, as server issue caused duplicate attempts    #
#       from several participants. As ID's got autogenerated at each link click, duplicates must   #
#       be removed manually. This script is for helping with that, and does have a hefty           #
#       conservative lean. I.e., makes sure there are zero duplicate attempts, at the cost of      #
#       removing some unique entries.                                                              #
# Important: No data is inspected for actual content, only for similarity of content, patterns of  #
#            missing and present data (as expected per experiment-flow), time-stamps, and time     #
#            spent per task/page. This is done prior to any and all other removal, i.e., includes  #
#            data that would be removed (e.g., due to being pilot-data) later on as well, as this  #
#            is the most transparent and blinded way of doing it.                                  #
# Kristoffer Klevjer - github.com/klvr - klevjer(a)gmail.com                                       #
####################################################################################################

# 01 Potential duplicate pairs ---------------------------------------------------------------------
pair01 <- c(55931, 78313)
pair02 <- c(59154, 52897)
pair03 <- c(43509, 90795)
pair04 <- c(63989, 91397, 39689)
pair05 <- c(21324, 40111)
pair06 <- c(88398, 40260)
pair07 <- c(74989, 34639, 59044, 69149, 60827, 54394)
pair08 <- c(94207, 81850)
pair09 <- c(93120, 26103, 82148)
pair10 <- c(39597, 74758)
pair11 <- c(33985, 79287)
pair12 <- c(66118) # x2
pair13 <- c(31930, 85696, 51537)
pair14 <- c(60561, 23601, 96651)
pair15 <- c(64825, 20261)
pair16 <- c(80003, 51788)
pair17 <- c(24530, 14444, 46939, 60789, 87634, 79913, 17441)
pair18 <- c(15604, 30292, 57683)
pair19 <- c(10392, 76016)
pair20 <- c(19892, 23726)
pair21 <- c(71035, 20223, 34810)
pair22 <- c(41672, 70123)
pair23 <- c(88340, 29733)
pair24 <- c(94878, 13885)
pair25 <- c(72936, 74680)
pair26 <- c(59674, 80042)
pair27 <- c(73560, 98734)
pair28 <- c(44690, 97939, 86253)
pair29 <- c(64622, 72742)
pair30 <- c(12546, 37269)
pair31 <- c(42738, 85583)
pair32 <- c(70734, 72022)
pair33 <- c(12837, 42976)
pair34 <- c(11551, 91225, 33324)

# 02 Function for printing suspected duplicates per task -------------------------------------------
## Input: df's (task-wise) with ID as first column
## Output: Printout of task-wise results grouped by pairs of sucpected duplicates

dupdetective <- function(variable) {
print("START")
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair01)) {
    if (variable[i,1]==pair01[x]) {
      print(variable[i,])
      print("Pair01")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair02)) {
    if (variable[i,1]==pair02[x]) {
      print(variable[i,])
      print("Pair02")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair03)) {
    if (variable[i,1]==pair03[x]) {
      print(variable[i,])
      print("Pair03")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair04)) {
    if (variable[i,1]==pair04[x]) {
      print(variable[i,])
      print("Pair04")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair05)) {
    if (variable[i,1]==pair05[x]) {
      print(variable[i,])
      print("Pair05")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair06)) {
    if (variable[i,1]==pair06[x]) {
      print(variable[i,])
      print("Pair06")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair07)) {
    if (variable[i,1]==pair07[x]) {
      print(variable[i,])
      print("Pair07")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair08)) {
    if (variable[i,1]==pair08[x]) {
      print(variable[i,])
      print("Pair08")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair09)) {
    if (variable[i,1]==pair09[x]) {
      print(variable[i,])
      print("Pair09")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair10)) {
    if (variable[i,1]==pair10[x]) {
      print(variable[i,])
      print("Pair10")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair11)) {
    if (variable[i,1]==pair11[x]) {
      print(variable[i,])
      print("Pair11")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair12)) {
    if (variable[i,1]==pair12[x]) {
      print(variable[i,])
      print("Pair12")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair13)) {
    if (variable[i,1]==pair13[x]) {
      print(variable[i,])
      print("Pair13")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair14)) {
    if (variable[i,1]==pair14[x]) {
      print(variable[i,])
      print("Pair14")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair15)) {
    if (variable[i,1]==pair15[x]) {
      print(variable[i,])
      print("Pair15")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair16)) {
    if (variable[i,1]==pair16[x]) {
      print(variable[i,])
      print("Pair16")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair17)) {
    if (variable[i,1]==pair17[x]) {
      print(variable[i,])
      print("Pair17")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair18)) {
    if (variable[i,1]==pair18[x]) {
      print(variable[i,])
      print("Pair18")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair19)) {
    if (variable[i,1]==pair19[x]) {
      print(variable[i,])
      print("Pair19")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair20)) {
    if (variable[i,1]==pair20[x]) {
      print(variable[i,])
      print("Pair20")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair21)) {
    if (variable[i,1]==pair21[x]) {
      print(variable[i,])
      print("Pair21")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair22)) {
    if (variable[i,1]==pair22[x]) {
      print(variable[i,])
      print("Pair22")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair23)) {
    if (variable[i,1]==pair23[x]) {
      print(variable[i,])
      print("Pair23")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair24)) {
    if (variable[i,1]==pair24[x]) {
      print(variable[i,])
      print("Pair24")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair25)) {
    if (variable[i,1]==pair25[x]) {
      print(variable[i,])
      print("Pair25")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair26)) {
    if (variable[i,1]==pair26[x]) {
      print(variable[i,])
      print("Pair26")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair27)) {
    if (variable[i,1]==pair27[x]) {
      print(variable[i,])
      print("Pair27")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair28)) {
    if (variable[i,1]==pair28[x]) {
      print(variable[i,])
      print("Pair28")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair29)) {
    if (variable[i,1]==pair29[x]) {
      print(variable[i,])
      print("Pair29")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair30)) {
    if (variable[i,1]==pair30[x]) {
      print(variable[i,])
      print("Pair30")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair31)) {
    if (variable[i,1]==pair31[x]) {
      print(variable[i,])
      print("Pair31")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair32)) {
    if (variable[i,1]==pair32[x]) {
      print(variable[i,])
      print("Pair32")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair33)) {
    if (variable[i,1]==pair33[x]) {
      print(variable[i,])
      print("Pair33")
    }
  }
}
for (i in 1:nrow(variable)) {
  for (x in 1:length(pair34)) {
    if (variable[i,1]==pair34[x]) {
      print(variable[i,])
      print("Pair34")
    }
  }
}
}

# 03 Going through each df task-wise ---------------------------------------------------------------
## Uncomment to run, must be done prior to removal in qualtrics_extraction.R (i.e., before line 801)

#dupdetective(students_misc)

#dupdetective(students_rq)

#dupdetective(students_rqTime)

#dupdetective(students_nfc)

#dupdetective(students_nfcTime)

#dupdetective(students_risk)

#dupdetective(students_mood)

#dupdetective(students_beadsNTLX)

#dupdetective(students_beadsDiff)

#dupdetective(students_diceNTLX)

#dupdetective(students_diceDiff)

#dupdetective(students_cape)

#dupdetective(students_capeTime)

#dupdetective(students_beadsA)

#dupdetective(students_beadsB)

#dupdetective(qualtrics_students)

## Additionally this was done for the source-data, to match similar meta-data

# 04 Results ---------------------------------------------------------------------------------------

# Pairs (multiple ID's per pair => same participant, first [time-wise], or only existing data kept).
## Pair 01: Keep 55931 for mood, demo, risk, dice, dice debrief. 78313 for rest.
## Pair 02: Keep 59154 for mood, demo, risk, dice, dice debrief. 52897 for rest.
## Pair 03: Keep 43509 all over, remove 90795.
## Pair 04: Keep 63989 all over, remove 91397 & 39689 (x2).
## Pair 05: Keep 21324 for mood, demo, risk, dice, dice debrief. 40111 for rest.
## Pair 06: Keep 88398 all over, remove 40260.
## Pair 07: Keep 74989 all over, remove 34639, 59044, 69149, 60827 & 54394.
## Pair 08: Keep 94207 all over, remove 81850.
## Pair 09: Keep 93120 for mood, demo, risk, dice, dice debrief. 82148 for rest. Remove 26103.
## Pair 10: Keep 39597 for mood, demo, risk, dice, dice debrief. 74758 for rest.
## Pair 11: Keep 33985 for mood, demo, risk, dice, dice debrief. 79287 for rest.
## Pair 12: Keep first row of 66118 all over. Remove second row of 66118.
## Pair 13: Keep 31930 all over, remove 85696 & 51537.
## Pair 14: Keep 60561 for mood, demo, risk, dice, dice debrief. 96651 for rest. Remove 23601.
## Pair 15: Keep 64825 for mood, demo, risk, dice, dice debrief. 20261 for rest.
## Pair 16: Keep 80003 all over, remove 51788.
## Pair 17: Remove all, 24530, 14444, 46939, 60789, 87634, 79913 & 17441.
## Pair 18: Keep 15604 all over, remove 30292 & 57683.
## Pair 19: Keep 10392 for mood, demo, risk, dice, dice debrief. 76016 for rest.
## Pair 20: Keep 19892 for mood, demo, risk, dice, dice debrief. 23726 for rest.
## Pair 21: Keep 71035 all over, remove 20223 & 34810.
## Pair 22: Keep 41672 for mood, demo, risk, dice, dice debrief. 70123 for rest.
## Pair 23: Remove all, 88340 & 29733.
## Pair 24: Keep 94878 all over, remove 13885.
## Pair 25: Keep 72936 all over, remove 74680.
## Pair 26: Keep 59674 for mood, demo, risk, dice, dice debrief. 80042 for rest.
## Pair 27: Keep 73560 for mood, demo, risk, dice, dice debrief. 98734 for rest.
## Pair 28: Keep 44690 for mood, demo, risk, dice, dice debrief. 86253 for rest. Remove 97939.
## Pair 29: Keep 64622 for mood, demo, risk, dice, dice debrief. 72742 for rest.
## Pair 30: Keep 37269 for all except dice and dice debriefs, there keep 12546.
## Pair 31: Keep 42738 all over, remove 85583 (x2).
## Pair 32: Remove all, 70734 & 72022.
## Pair 33: Keep 12837 for mood, demo, risk, dice, dice debrief. 42976 for rest.
## Pair 34: Keep 11551 all over, remove 91225 & 33324.

# 05 Create removal variables ----------------------------------------------------------------------
## Create task-wise variables containing ID's to be removed

students_mood_remove <-      c(pair01[pair01!=55931], pair02[pair02!=59154], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=21324], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=93120],
                               pair10[pair10!=39597], pair11[pair11!=33985], pair13[pair13!=31930],
                               pair14[pair14!=60561], pair15[pair15!=64825], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=10392],
                               pair20[pair20!=19892], pair21[pair21!=71035], pair22[pair22!=41672],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=59674], pair27[pair27!=73560], pair28[pair28!=44690],
                               pair29[pair29!=64622], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=12837], pair34[pair34!=11551])
students_misc_remove <-      c(pair01[pair01!=55931], pair02[pair02!=59154], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=21324], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=93120],
                               pair10[pair10!=39597], pair11[pair11!=33985], pair13[pair13!=31930],
                               pair14[pair14!=60561], pair15[pair15!=64825], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=10392],
                               pair20[pair20!=19892], pair21[pair21!=71035], pair22[pair22!=41672],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=59674], pair27[pair27!=73560], pair28[pair28!=44690],
                               pair29[pair29!=64622], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=12837], pair34[pair34!=11551])
students_risk_remove <-      c(pair01[pair01!=55931], pair02[pair02!=59154], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=21324], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=93120],
                               pair10[pair10!=39597], pair11[pair11!=33985], pair13[pair13!=31930],
                               pair14[pair14!=60561], pair15[pair15!=64825], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=10392],
                               pair20[pair20!=19892], pair21[pair21!=71035], pair22[pair22!=41672],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=59674], pair27[pair27!=73560], pair28[pair28!=44690],
                               pair29[pair29!=64622], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=12837], pair34[pair34!=11551])
students_dice_remove <-      c(pair01[pair01!=55931], pair02[pair02!=59154], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=21324], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=93120],
                               pair10[pair10!=39597], pair11[pair11!=33985], pair13[pair13!=31930],
                               pair14[pair14!=60561], pair15[pair15!=64825], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=10392],
                               pair20[pair20!=19892], pair21[pair21!=71035], pair22[pair22!=41672],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=59674], pair27[pair27!=73560], pair28[pair28!=44690],
                               pair29[pair29!=64622], pair30[pair30!=12546], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=12837], pair34[pair34!=11551])
students_diceNTLX_remove <-  c(pair01[pair01!=55931], pair02[pair02!=59154], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=21324], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=93120],
                               pair10[pair10!=39597], pair11[pair11!=33985], pair13[pair13!=31930],
                               pair14[pair14!=60561], pair15[pair15!=64825], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=10392],
                               pair20[pair20!=19892], pair21[pair21!=71035], pair22[pair22!=41672],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=59674], pair27[pair27!=73560], pair28[pair28!=44690],
                               pair29[pair29!=64622], pair30[pair30!=12546], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=12837], pair34[pair34!=11551])
students_diceDiff_remove <-  c(pair01[pair01!=55931], pair02[pair02!=59154], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=21324], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=93120],
                               pair10[pair10!=39597], pair11[pair11!=33985], pair13[pair13!=31930],
                               pair14[pair14!=60561], pair15[pair15!=64825], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=10392],
                               pair20[pair20!=19892], pair21[pair21!=71035], pair22[pair22!=41672],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=59674], pair27[pair27!=73560], pair28[pair28!=44690],
                               pair29[pair29!=64622], pair30[pair30!=12546], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=12837], pair34[pair34!=11551])
students_rq_remove <-        c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_rqTime_remove <-    c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_nfc_remove <-       c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_nfcTime_remove <-   c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_beadsNTLX_remove <- c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_beadsDiff_remove <- c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_cape_remove <-      c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_beadsA_remove <-    c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])
students_beadsB_remove <-    c(pair01[pair01!=78313], pair02[pair02!=52897], pair03[pair03!=43509],
                               pair04[pair04!=63989], pair05[pair05!=40111], pair06[pair06!=88398],
                               pair07[pair07!=74989], pair08[pair08!=94207], pair09[pair09!=82148],
                               pair10[pair10!=74758], pair11[pair11!=79287], pair13[pair13!=31930],
                               pair14[pair14!=96651], pair15[pair15!=20261], pair16[pair16!=80003],
                               pair17,                pair18[pair18!=15604], pair19[pair19!=76016],
                               pair20[pair20!=23726], pair21[pair21!=71035], pair22[pair22!=70123],
                               pair23,                pair24[pair24!=94878], pair25[pair25!=72936],
                               pair26[pair26!=80042], pair27[pair27!=98734], pair28[pair28!=86253],
                               pair29[pair29!=72742], pair30[pair30!=37269], pair31[pair31!=42738],
                               pair32,                pair33[pair33!=42976], pair34[pair34!=11551])

# 06 Create ID renaming variable -------------------------------------------------------------------
## Create a df with column 1: ID to be used, column 2: ID to be swapped
## Only applicable for the pairs where multiple ID's are kept (e.g., not 'all over')

students_renameID <- rbind(c(55931, 78313), c(59154, 52897), c(21324, 40111), c(93120, 82148),
                           c(39597, 74758), c(33985, 79287), c(60561, 96651), c(64825, 20261),
                           c(10392, 76016), c(19892, 23726), c(41672, 70123), c(59674, 80042),
                           c(73560, 98734), c(44690, 86253), c(64622, 72742), c(37269, 12546),
                           c(12837, 42976))